services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: web
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql+psycopg2://postgress:postgress@db/postgress
    depends_on:
      - db

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: streamlit
    ports:
      - "8501:8501"
    environment:
      WEB_URL: http://web:5000
      WEBSCRAPER_URL: http://webscraper:5001
    depends_on:
      - web

  webscraper:
    build:
      context: .
      dockerfile: Dockerfile.webscraper
    container_name: webscraper
    ports:
      - "5001:5001"
    environment:
      WEB_URL: http://web:5000/home
    depends_on:
      - web

  db:
    image: postgres:18
    environment:
      POSTGRES_PASSWORD: postgress
      POSTGRES_USER: postgress
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/18/docker
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  postgres-db:
    driver: local