services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: web
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db/postgres
    networks:
      - teste_net
    depends_on:
      - db

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: streamlit
    ports:
      - "8501:8501"
    environment:
      WEB_URL: http://web:5000
      WEBSCRAPER_URL: http://webscraper:5001
    networks:
      - teste_net
    depends_on:
      - web

  webscraper:
    build:
      context: .
      dockerfile: Dockerfile.webscraper
    container_name: webscraper
    ports:
      - "5001:5001"
    environment:
      WEB_URL: http://web:5000/home
    networks:
      - teste_net
    depends_on:
      - web

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    networks:
      - teste_net
    volumes:
      - postgres-db:/var/lib/postgresql/data
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

networks:
  teste_net:
    driver: bridge

volumes:
  postgres-db:
    driver: local
