services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "5000:5000"
    env_file:
      - ./.env

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    depends_on:
      - web

  webscraper:
    build:
      context: .
      dockerfile: Dockerfile.webscraper
    depends_on:
      - web